### ISSUE TITLE
Test cases failed with EI 6.2.0

### ISSUE THREAD

**Issue by Nirthika** [wso2-extensions/esb-connector-jira#11]
**Description:**
14 Tests are failing with
     ERROR - Axis2Sender Unexpected error during sending message out

Other than that 4 tests are failing:   testCreateComponentWithMandatoryParameters(org.wso2.carbon.connector.integration.test.jira.JiraConnectorIntegrationTest): expected:<201> but was:<400>
  testCreateComponentWithOptionalParameters(org.wso2.carbon.connector.integration.test.jira.JiraConnectorIntegrationTest): expected:<201> but was:<400>
  testGetCommentByIdWithOptionalParameters(org.wso2.carbon.connector.integration.test.jira.JiraConnectorIntegrationTest): JSONObject["renderedBody"] not found.
  testGetCommentByIdWithMandatoryParameters(org.wso2.carbon.connector.integration.test.jira.JiraConnectorIntegrationTest): JSONObject["author"] not found.

**Comment by anupama-pathirage** [comment]
Closing this as this is an issue in older version of EI
